name: Create new `git tag`, create new GitHub release and publish to NPM

on:
  workflow_call:
    inputs:
      node-version:
        description: "Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0"
        default: 12
        required: false
        type: string

      package-manager:
        description: "Used to specify a package manager for caching in the default directory. Supported values: npm, yarn, pnpm"
        default: npm
        required: false
        type: string

      registry-url:
        description: Optional registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKEN'
        default: "https://registry.npmjs.org"
        required: false
        type: string

    secrets:
      npm-automation-token:
        description: |
          NPM automation token authorized to publish package.
          https://docs.npmjs.com/creating-and-viewing-access-tokens
        required: true

jobs:
  create_git_tag:
    name: Create new `git tag`
    runs-on: ubuntu-latest
    timeout-minutes: 20
    outputs:
      new_tag: ${{ steps.detect_then_tag.outputs.tag }}
      new_version: ${{ steps.detect_then_tag.outputs.current-version }}
      old_version: ${{ steps.detect_then_tag.outputs.previous-version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # Required to ensure git history is properly checked:
          # https://github.com/salsify/action-detect-and-tag-new-version/blob/v2.0.1/README.md?plain=1#L11
          fetch-depth: 2

      - name: Detect and tag new version
        id: detect_then_tag
        uses: salsify/action-detect-and-tag-new-version@v2

  create_github_release:
    if: ${{ needs.create_git_tag.outputs.new_tag }}
    name: Create new GitHub release
    needs: create_git_tag
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: ncipollo/release-action@v1
        with:
          body: "\
            Changelog: \
            ${{ github.server_url }}/${{ github.repository }}\
            /compare/\
            v${{ needs.create_git_tag.outputs.old_version }}...v${{ needs.create_git_tag.outputs.new_version }}\
            "
          name: Release ${{ needs.create_git_tag.outputs.new_tag }}
          tag: ${{ needs.create_git_tag.outputs.new_tag }}

  publish_npm:
    if: ${{ needs.create_git_tag.outputs.new_tag }}
    name: Publish to NPM
    needs: create_git_tag
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node-version }}
          # Required if we want to authenticate during the `npm publish`:
          # https://github.com/actions/setup-node/blob/v2.4.1/action.yml#L15-L16
          registry-url: ${{ inputs.registry-url }}

      - name: Install Dependencies
        run: |
          if [ "${{ inputs.package-manager }}" = "npm" ]; then
            npm ci
          elif [ "${{ inputs.package-manager }}" = "yarn" ]; then
            yarn install --frozen-lockfile
          elif [ "${{ inputs.package-manager }}" = "pnpm" ]; then
            pnpm install --frozen-lockfile
          else
            echo "Unsupported package manager: ${{ inputs.package-manager }}"
            exit 1
          fi

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm-automation-token }}
